# Generated by Django 5.2.5 on 2025-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='parserapp.author'),
        ),
    ]
