# Generated by Django 5.2.5 on 2025-08-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0003_remove_book_author_id_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
