# Generated by Django 5.2.5 on 2025-08-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0004_rename_author_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_href',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
