# Generated by Django 5.2.5 on 2025-08-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0005_book_img_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img_href',
            field=models.ImageField(blank=True, null=True, upload_to='books'),
        ),
    ]
